@echo off

set PLATFORMNAME=%1
set CONFIGURATIONNAME=%2
set BINARY=%3

REM strip off the trailing and leading " by dropping those characters
set PLATFORMNAME=%PLATFORMNAME:~1,-1%
set CONFIGURATIONNAME=%CONFIGURATIONNAME:~1,-1%
set BINARY=%BINARY:~1,-1%

echo PLATFORMNAME=%PLATFORMNAME%
echo CONFIGURATIONNAME=%CONFIGURATIONNAME%
echo BINARY=%BINARY%

IF NOT EXIST dist md dist
IF NOT EXIST "dist\%PLATFORMNAME%" md "dist\%PLATFORMNAME%"
IF NOT EXIST "dist\%PLATFORMNAME%\%CONFIGURATIONNAME%" md "dist\%PLATFORMNAME%\%CONFIGURATIONNAME%"
echo Copying binary
copy "%CONFIGURATIONNAME%\%PLATFORMNAME%\%BINARY%" "dist\%PLATFORMNAME%\%CONFIGURATIONNAME%"
