.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BARRYDESKTOP 1 "September 24, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.B barrydesktop
\- Barry Project's control panel for the BlackBerry handheld
.SH SYNOPSIS
.B barrydesktop
[-?][-d]
.SH DESCRIPTION
.PP
.B barrydesktop
is a GUI application which provides general control of your Blackberry
handheld devices.

This application is still in development.

.SH AUTHOR
.nh
.B barrydesktop
is part of the Barry project.
This manual page was written by Chris Frey.
.SH SEE ALSO
.PP
http://www.netdirect.ca/software/packages/barry

