#!/bin/sh -e

everything() {
	# set ownership for ppp options files
	for f in /etc/ppp/peers/barry-*
	do
		chown root:dip "$f"
	done

	# set permissions for chatscripts
	for f in /etc/chatscripts/barry-*.chat
	do
		chown root:dip "$f"
		chmod 0640 "$f"
	done
}

case "$1" in
	configure)
		everything
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	echo "postinst called with unknown argument '$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0

