debian/tmp/usr/bin/barrydesktop
debian/tmp/usr/lib/barry/barrydesktop/bsyncjail
debian/tmp/usr/lib/barry/barrydesktop/blistevo
debian/tmp/usr/share/barry/desktop/0.22/*
debian/tmp/usr/share/barry/desktop/0.40/*
debian/tmp/usr/share/barry/desktop/images/*
debian/tmp/usr/share/man/man1/barrydesktop.1
debian/tmp/usr/lib/libosyncwrap.so.*
debian/tmp/usr/include/barry*/osyncwrap/*
debian/tmp/usr/share/locale/*/LC_MESSAGES/barrydesktop.mo
debian/tmp/usr/share/locale/*/LC_MESSAGES/barryosyncwrap.mo

