Barry: Barry::DBDataBuilder Class Reference
Barry::DBDataBuilder Class Reference
#include <builder.h>
Detailed Description
Wrapper class around a DBData object, to make it easy to pass a DBData object into a function or API that requires a builder.
The main advantage to this is that the Builder API allows for movement of data, depending on the required offsets.
Definition at line 115 of file builder.h.
Public Member Functions
virtual bool BuildRecord (DBData &data, size_t &offset, const IConverter *ic)
Called to build the record field data.
virtual bool FetchRecord (DBData &data, const IConverter *ic)
Same as BuildRecord, but does not care about any offsets.
virtual bool EndOfFile () const
Sometimes a builder can have multiple databases stored in it, so when Build/Fetch returns false, check if there is more data with this function.
Member Function Documentation
bool Barry::DBDataBuilder::BuildRecord (DBData & data, size_t & offset, const IConverter * ic) [virtual]
Called to build the record field data.
Store the raw data in data, using offset to know where to write. Be sure to update offset, and be sure to adjust the size of the data packet (possibly with Data::ReleaseBuffer()).
Returns true if successful, and false if at the end of the series. Note that if EndOfFile() is false after this function returns false, then there may be another series available, which the next call to BuildRecord() will determine.
Implements Barry::Builder.
Definition at line 41 of file builder.cc.
References Barry::DBData::CopyMeta(), Barry::DBData::GetData(), Barry::DBData::GetOffset(), Barry::DBData::SetOffset(), and Barry::DBData::UseData().
bool Barry::DBDataBuilder::FetchRecord (DBData & data, const IConverter * ic) [virtual]
Same as BuildRecord, but does not care about any offsets.
The caller should call DBData::GetOffset() afterward to discover if there is an offset to the result.
This is usually the fastest of the two functions, since extra copying may be required if a specific offset is given. When building records from Record classes, both functions are the same speed. But when building records from the device, the device decides the offset, so FetchRecord() is faster, since BuildRecord requires a copy to adjust to the right offset.
The caller should use the function that results in the least amount of copying for the caller. If the caller doesn't care about where the resulting record is in data, use FetchRecord().
Implements Barry::Builder.
Definition at line 68 of file builder.cc.
bool Barry::DBDataBuilder::EndOfFile () const [virtual]
Sometimes a builder can have multiple databases stored in it, so when Build/Fetch returns false, check if there is more data with this function.
This function is not used by database-oriented functions, but by pipe- oriented functions.
Implements Barry::Builder.
Definition at line 74 of file builder.cc.
The documentation for this class was generated from the following files:
builder.h
builder.cc