#!/usr/bin/perl

# dump-simple version 0.1

# Copyright (C) 2008, ashley willis <barry@venamous.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License in the COPYING file at the
# root directory of this project for more details.

# backs up each DB in phone to file <DB>.dump

`bcharge`;		# inits phone
@list = `btool -t`;	# gets list of databases
$i = 0;

foreach (@list) {
  if (s/    Database: 0x[\da-f][\da-f]? //) {
    ($db[$i], $records[$i]) = split(/ \(records: /);
    $records[$i] =~ s/\)$//;
    print "### $i $db[$i] ###\n";
    print `btool -n -d $db[$i] > $db[$i].dump`;
    $i++;
  }
}
print "count=$i\n";
